[package]
name = "asciify"
authors = ["Grazen0"]
description = "Blazingly fast image-to-ASCII converter"
homepage = "https://github.com/Grazen0/asciify"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
image = "0.25.5"
term_size = "0.3.2"
